import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { TweetComponent } from '../../components/Tweet/TweetComponent'
import { ITweet } from '@/models/Tweet'
import { useCallback, useEffect, useState } from 'react'
import useSWRInfinite from "swr/infinite";
import { useSWRConfig } from 'swr'
import { useRouter } from 'next/router'
import useUserCache from '@/hooks/useUserCache'
import UserDetails from '@/components/UserDetails'


export default function UserPage() {
    const router = useRouter()
    const { user_id } = router.query
    // console.log(user_id)

    if (!user_id) {
        return (
            <div>
                <Head>
                    <title>Home</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>


                {/* {
            JSON.stringify(TweetFeed)
          } */}
            </div>
        )
    } else {
        return (
            <UserInfo author_id={user_id} />
        )
    }
}

function UserInfo({ author_id }: { author_id: string }) {
    const { authorDetails, loading: authorLoading, error: authorError } = useUserCache(author_id as string | undefined)

    if (authorDetails) {
        return (
            <div className='w-full'>
                <Head>
                    <title>{authorDetails.user_name}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className="w-full">
                    <h1 className='flex w-full space-x-10 p-3 sticky top-0 opacity-90 bg-white'>
                        <button
                            onClick={(event) => { event.preventDefault(); router.back() }}>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                            </svg>
                        </button>
                        <span className='text-xl font-semibold'>
                            {authorDetails.name}
                        </span>
                    </h1>
                    {
                        <UserDetails authorDetails={authorDetails} />
                    }
                </div>

                {/* {
                JSON.stringify(TweetFeed)
              } */}
            </div>
        )
    }else{
        return (
            <div></div>
        )
    }
}