import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Tweet from '@/components/Tweet'
import { ITweet } from '@/models/Tweet'

const inter = Inter({ subsets: ['latin'] })

const dataTweet : ITweet = {
  _id:'001',
  parent_tweet:null,
  text: "Meow Meow Meow Meow billi karti meow meow",
  attachments:undefined,
  author:'someone',
  authorDetails:{
    _id:'user01',
    name:"Siddhant Deshmukh",
    user_name:"siddh01",
    avatar:undefined,
    about:'Siddhant is a good boy'
  },
  has_liked:false,
  has_retweet:false,

  num_views:0,
  num_comments:0,
  num_quotes:0,
  num_likes:0,
  num_retweet:0,
  time : new Date()
  
}
console.log(dataTweet)

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      
    </>
  )
}
